// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7U63q-P2gwmMQ-TCEK3f-gwczugfnhQ',
    appId: '1:555917250222:web:20a658e1fbccef0580673f',
    messagingSenderId: '555917250222',
    projectId: 'eduvian-9c08e',
    authDomain: 'eduvian-9c08e.firebaseapp.com',
    storageBucket: 'eduvian-9c08e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBi0GdGMFmdTERABf_OsdpA69smXU-sg',
    appId: '1:555917250222:android:20015bccc90a1af480673f',
    messagingSenderId: '555917250222',
    projectId: 'eduvian-9c08e',
    storageBucket: 'eduvian-9c08e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wDZdj-uEDgpx64B47kjGSpqocEkWDjo',
    appId: '1:555917250222:ios:b54c4d1e5e51088a80673f',
    messagingSenderId: '555917250222',
    projectId: 'eduvian-9c08e',
    storageBucket: 'eduvian-9c08e.firebasestorage.app',
    iosBundleId: 'com.example.eduvian',
  );
}
